# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c0c36a73657e5306a9b80dba4c3318263d83831695954865e3b8a94d6c90ac0a5a79c7c5947b242d3e73c3ad15add3c26fa7e64abe0d06f66425ddf9bcc45a94

test:
  secret_key_base: 1b68d20ddf3c3ab830d24149c968b81162752e190769a79f58486110a2bea9a42ed8260c05e0dc08057a8327c4ad62cada8549293b5ed576ca8a15f28cc8d334

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
